### ISSUE TITLE
Error pushing data to sample dashboard 

### ISSUE THREAD

**Issue by csotodos** [Smashing/smashing#122]
Hi team,

I have just installed the smashing project in my Raspberry Pi to create a temperature and humidity monitor. 

I'm playing with the sample project before I start working on mine, but I have followed all the steps to install the clean sample dashboard and when I try to send data as stated in the sample, I'm retrieving the following error:
```
pi@monitor:~/smashing-dashboars/my_dashboard $ curl -d '{ "auth_token": "YOUR_AUTH_TOKEN", "text": "Cesar!" }' http://192.168.1.47:3030/widgets/welcome
TypeError: can't dup NilClass
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1092:in `dup'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1092:in `block in dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1092:in `each'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1092:in `dispatch!'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `block in call!'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `block in invoke'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `catch'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1076:in `invoke'        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:924:in `call!'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:913:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/json_csrf.rb:26:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/base.rb:50:in `call'
        /var/lib/gems/2.3.0/gems/rack-protection-2.0.5/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:231:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:224:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/show_exceptions.rb:22:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:194:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1957:in `call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `block in call'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1729:in `synchronize'
        /var/lib/gems/2.3.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1502:in `call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:68:in `block in call'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `each'
        /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/urlmap.rb:53:in `call'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /var/lib/gems/2.3.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'        /var/lib/gems/2.3.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        /var/lib/gems/2.3.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
        /usr/local/bin/thin:22:in `load'
        /usr/local/bin/thin:22:in `<top (required)>'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
        /var/lib/gems/2.3.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
        /usr/local/bin/bundle:22:in `load'
        /usr/local/bin/bundle:22:in `<main>'
```

Thanks for your time. 

Regards, 
César.

**Comment by NoelzeN** [comment]
@csotodos did you find a way to solve this by change? Having the same issue using Smashing in a Docker Container (For some reason I don't have the issue with a normal installation)

**Comment by csotodos** [comment]
No, I was not able to develop the project I had in mind because I was not able to send the data, sorry @NoelzeN.

**Comment by NoelzeN** [comment]
Thanks for your quick reply @csotodos 
I tried a few things and managed to get it (partially) working by forcing sinatra and sinatra-contrib gems to be version 2.0.8 (default installed version was 2.0.5). That way I had another issue: Whatever I tried, I got error "Invalid API key" when trying to push data to a widget. Didn't find a solution to that and since I anyway want to set it up in a closed environment, I simply manually removed the auth check from the app.rb file (Around line 112 in https://github.com/Smashing/smashing/blob/master/lib/dashing/app.rb ). Now everything seems to be running, however SECURITY IS COMPLETELY GONE NOW (In case someone stumbled upon this post when searching for the issue like I did. Be warned, but maybe you find something helpful from my experience)
