### ISSUE TITLE
Clean Install on Raspberry - ConnectionError 

### ISSUE THREAD

**Issue by mdrewanz** [Smashing/smashing#143]
After a clean install of Raspbian and smashing, the start of smashing yields an error not being able to establish a connection to the server as shown below:

```
{ 2010324 rufus-scheduler intercepted an error:
  2010324   job:
  2010324     Rufus::Scheduler::EveryJob "10m" {:first_in=>0}
  2010324   error:
  2010324     2010324
  2010324     HTTP::ConnectionError
  2010324     failed to connect: Connection reset by peer - SSL_connect
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/timeout/null.rb:27:in `connect'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/timeout/null.rb:27:in `connect_ssl'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/timeout/null.rb:36:in `start_tls'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/connection.rb:162:in `start_tls'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/connection.rb:46:in `initialize'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/client.rb:67:in `new'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/client.rb:67:in `perform'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/client.rb:30:in `request'
  2010324       /var/lib/gems/2.3.0/gems/http-3.3.0/lib/http/chainable.rb:20:in `get'
  2010324       /var/lib/gems/2.3.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:36:in `public_send'
  2010324       /var/lib/gems/2.3.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:36:in `perform'
  2010324       /var/lib/gems/2.3.0/gems/twitter-6.2.0/lib/twitter/search_results.rb:26:in `initialize'
  2010324       /var/lib/gems/2.3.0/gems/twitter-6.2.0/lib/twitter/rest/search.rb:33:in `new'
  2010324       /var/lib/gems/2.3.0/gems/twitter-6.2.0/lib/twitter/rest/search.rb:33:in `search'
  2010324       /home/pi/dashboard/sweet_dashboard/jobs/twitter.rb:17:in `block in <top (required)>'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:210:in `do_call'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:254:in `trigger_now'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:296:in `block (3 levels) in start_work_thread'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:299:in `block (2 levels) in start_work_thread'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `loop'
  2010324       /var/lib/gems/2.3.0/gems/rufus-scheduler-3.4.2/lib/rufus/scheduler/jobs.rb:285:in `block in start_work_thread'
  2010324   tz:
  2010324     ENV['TZ']: 
  2010324     Time.now: 2019-07-24 08:39:20 -0300
  2010324     local_tzone: #<TZInfo::DataTimezone: America/Sao_Paulo>
  2010324   et-orbi:
  2010324     (etz:nil,tnz:"-03",tziv:"2.0.0",tzidv:nil,rv:"2.3.3",rp:"arm-linux-gnueabihf",win:false,rorv:nil,astz:nil,eov:"1.2.1",eotnz:#<TZInfo::DataTimezone: America/Sao_Paulo>,eotnfz:"-0300",eotlzn:"America/Sao_Paulo",eotnfZ:"-03",debian:"America/Sao_Paulo",centos:nil,osx:"America/Sao_Paulo")
  2010324   scheduler:
  2010324     object_id: 4946064
  2010324     opts:
  2010324       {}
  2010324       frequency: 0.3
  2010324       scheduler_lock: #<Rufus::Scheduler::NullLock:0x96e340>
  2010324       trigger_lock: #<Rufus::Scheduler::NullLock:0x96e2c8>
  2010324     uptime: 54002.069212436676 (15h2s79)
  2010324     down?: false
  2010324     threads: 5
  2010324       thread: #<Thread:0x91b510>
  2010324       thread_key: rufus_scheduler_4946064
  2010324       work_threads: 4
  2010324         active: 1
  2010324         vacant: 3
  2010324         max_work_threads: 28
  2010324       mutexes: {}
  2010324     jobs: 4
  2010324       at_jobs: 0
  2010324       in_jobs: 0
  2010324       every_jobs: 4
  2010324       interval_jobs: 0
  2010324       cron_jobs: 0
  2010324     running_jobs: 1
  2010324     work_queue: 0
} 2010324 .
```
Any clues on what is missing / wrong ??

**Comment by lewis-fidlers** [comment]
Hi, 

Have a look at this file: `https://github.com/Smashing/smashing/blob/master/templates/project/jobs/twitter.rb` Since I'm assuming you haven't modified anything yet you probably want to set up your API keys etc.

As the error points out the job itself is here: `/home/pi/dashboard/sweet_dashboard/jobs/twitter.rb:17`

**Comment by kinow** [comment]
@mdrewanz closing as it appears to be an issue with the Twitter gem use (thanks @lewis-fidlers). Feel free to comment/re-open if necessary.

We may disable that gem by default #163 too, which would cause less issues like this :+1:
