### ISSUE TITLE
Smashing won't load: bundler: failed to load command: thin (/usr/local/bin/thin)

### ISSUE THREAD

**Issue by jason-mehmel** [Smashing/smashing#193]
**Describe the bug**

When I type **smashing start** I get an error response as well as a traceback of the commands.

I will produce the traceback here!

```bash
2022-05-19 20:39:02 -0600 Thin web server (v1.8.1 codename Infinite Smoothie)
2022-05-19 20:39:02 -0600 Maximum connections set to 1024
2022-05-19 20:39:02 -0600 Listening on 0.0.0.0:3030, CTRL+C to stop
bundler: failed to load command: thin (/usr/local/bin/thin)
Traceback (most recent call last):
	28: from /usr/local/bin/bundle:23:in `<main>'
	27: from /usr/local/bin/bundle:23:in `load'
	26: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
	25: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	24: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
	23: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
	22: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	21: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
	20: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	19: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	18: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	17: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
	16: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
	15: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
	14: from /var/lib/gems/2.7.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
	13: from /usr/local/bin/thin:23:in `<top (required)>'
	12: from /usr/local/bin/thin:23:in `load'
	11: from /var/lib/gems/2.7.0/gems/thin-1.8.1/bin/thin:6:in `<top (required)>'
	10: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:159:in `run!'
	 9: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/runner.rb:203:in `run_command'
	 8: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/controllers/controller.rb:87:in `start'
	 7: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
	 6: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
	 5: from /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 4: from /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 3: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/base.rb:65:in `block in start'
	 2: from /var/lib/gems/2.7.0/gems/thin-1.8.1/lib/thin/backends/tcp_server.rb:16:in `connect'
	 1: from /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
/var/lib/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
```

**To Reproduce**
1. Go to 'project folder'
2. type  **smashing start**
3. See error: bundler: failed to load command: thin (/usr/local/bin/thin)

This is followed by a traceback.

**Expected behavior**
That the Smashing project would load!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 21.10]
 - Browser [e.g. firefox]
 - Version [e.g. 100]
 - Ruby and gems versions [e.g. ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]]
Ruby: 2.7
Rubygems: 3.2.5-2

**Additional context**

**Notes**

1. Check the [Troubleshooting Guide](https://github.com/Dashing-io/dashing/wiki#how-tos) in the wiki.
2. Ask in the [Gitter Chat Room](https://gitter.im/Smashing/Lobby) - please do not submit issues for support requests.
3. Use the [GitHub Issue Search](https://help.github.com/articles/searching-issues/) to check if the issue has already been reported.

**Comment by JCluzet** [comment]
same problem

**Comment by kinow** [comment]
Sorry, haven't had time to work on this yet.

**Comment by JCluzet** [comment]
I just find... one smashing was already start (port is in use) was precise at the end

**Comment by kinow** [comment]
>no acceptor (port is in use or requires root privileges) (RuntimeError)

Would it be possible, when this error occurs, to run a command to list the ports used, please? For example, for Ubuntu Linux this could work: `netstat -tlnp`. And confirm there's nothing already listening on port `3030`.

**Comment by kinow** [comment]
Closing due to inactivity, but if others find a way to reproduce it and can confirm via `netstat` or starting a separate process as @oyohimura suggested, please let us know and provide a minimum reproducible test case :+1:
