### ISSUE TITLE
SystemD in Centos 7

### ISSUE THREAD

**Issue by Bond246** [Smashing/smashing#69]
Hello,

i'm trying to start smashing as a service on Centos 7.3 which is using systemd. I need to use Centos 7 at work for this project.

First idea was to use a common init script which is working perfectly if i use it manually:
```
#!/bin/bash
### BEGIN INIT INFO
# Provides: dashing
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop service dashing
# Description: Dashing
### END INIT INFO

# Must be a valid filename
NAME=smashing
DASHING_DIR=/home/dashing/untertitel
ESEC_DIR=/home/dashing/.rbenv/versions/2.2.7/bin
PID_DIR=$DASHING_DIR/tmp/pids
GEM_HOME=/usr/local/share/gems/gems
PIDFILE=$PID_DIR/thin.pid

#store dashing pid in $PID, else empty string
if [ -f $PIDFILE ]; then
   PID=$(<"$PIDFILE")
   else echo ""
fi

case "$1" in
   start)
        echo "Starting Dashing..."
        cd $DASHING_DIR; $ESEC_DIR/smashing start -d -p 3030 && sleep 2s
        echo "Success!"
   ;;
   stop)
        echo "" && echo "Killing Dashing..." && sleep 3s
        if [ -f $PIDFILE ]; then
           kill $PID && sleep 2s && echo "RIP Dashing"
           else echo "Stop beating the dead horse (it's already dead!)"
        fi
   ;;
   logs)
        echo "See the logs of the Dashing."
        tail -f $DASHING_DIR/log/thin.log
   ;;
   status)
        # Check to see if the process is running
        ps aux|grep -i smashing
   ;;

   *)
        echo "Dashing"
        echo $"Usage: $0 {start|stop|restart|status|logs}"
        exit 1
        esac
exit 0
```

systemd service file:
```
[Unit]
Description=Dashing
Before=syslog.target network.targe dashing.service

[Service]
TimeoutStartSec=0
Type=oneshot
RemainAfterExit=yes
ExecStart=/home/dashing/dashing-start.sh start
ExecStop=/home/dashing/dashing-start.sh stop

[Install]
WantedBy=multi-user.target
```

journalctl says that:
```
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: Starting Dashing...
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: bundler: failed to load command: thin (/usr/local/bin/thin)
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: Bundler::GemNotFound: Could not find smashing-1.0.0 in any of the sources
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/gems/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
Jun 07 11:39:27 srv-sub-dash dashing-start.sh[14549]: /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
Jun 07 11:39:29 srv-sub-dash dashing-start.sh[14549]: Success!
Jun 07 11:39:29 srv-sub-dash polkitd[4794]: Unregistered Authentication Agent for unix-process:14543:6993938 (system bus name :1.123, object path /org/freedesktop/Policy
Jun 07 11:39:29 srv-sub-dash systemd[1]: Started Dashing.
-- Subject: Unit dashing.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dashing.service has finished starting up.
--
-- The start-up result is done.
```
systemd thinks that starting was ok. I know that the thin server isn't started and no other process of smashing is running. 

Any idea how to get this running?

**Comment by dfbm** [comment]
Just avoid these old init.d scripts, systemd is better off without them.
Here's what I use to start our dashboard (still using dashing):
```
[Unit]
Wants=network-online.target
After=network-online.target

[Service]
Restart=always
RestartSec=60
User=dashing_t
Group=dashing_t
Type=simple
WorkingDirectory=/home/dashing/dashing
ExecStart=/usr/bin/ruby -dv /home/dashing/.gem/ruby/2.1.0/bin/dashing start

# Security settings...
PrivateTmp=true
PrivateDevices=true
ProtectSystem=full
ProtectHome=true
MountFlags=private
NoNewPrivileges=true

# Environment
Environment=BUNDLE_PATH=/home/dashing/.bundle "PATH=/usr/bin:/bin:/home/dashing/.gem/ruby/2.1.0/bin"

[Install]
WantedBy=multi-user.target
```

After saving that file as /etc/systemd/system/dashing.service and adjusting the paths run:
```
systemctl daemon-reload
systemctl enable dashing
systemctl start dashing
systemctl status dashing
```

**Comment by Bond246** [comment]
Thanks for your answer. The problem is, this init script works, for now systemd just seems to be work for me where i could do better things :-)

This is my service script now:
```
[Unit]
Wants=network-online.target
After=network-online.target

[Service]
Restart=always
RestartSec=60
User=root
Group=root
Type=simple
WorkingDirectory=/home/dashing/untertitel
ExecStart=/usr/bin/ruby -dv /home/dashing/.rbenv/versions/2.2.7/bin/smashing start

# Security settings...
PrivateTmp=true
PrivateDevices=true
ProtectSystem=full
MountFlags=private
NoNewPrivileges=true

# Environment
Environment=BUNDLE_PATH=/home/dashing/.bundle "PATH=/usr/bin:/bin:/home/dashing/bin:/home/dashing/.rbenv/versions/2.2.7/bin"

[Install]
WantedBy=multi-user.target
```

And this is the output.
```
Jun 07 15:59:14 srv-sub-dash systemd[1]: dashing.service holdoff time over, scheduling restart.
Jun 07 15:59:14 srv-sub-dash systemd[1]: Started Dashing.
Jun 07 15:59:14 srv-sub-dash systemd[1]: Starting Dashing...
Jun 07 15:59:14 srv-sub-dash ruby[15566]: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
Jun 07 15:59:14 srv-sub-dash ruby[15566]: Exception `LoadError' at /usr/local/share/ruby/site_ruby/rubygems.rb:1355 - cannot load such file -- rubygems/defaults/ruby
Jun 07 15:59:14 srv-sub-dash ruby[15566]: Exception `LoadError' at /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- abrt
Jun 07 15:59:14 srv-sub-dash ruby[15566]: Exception `LoadError' at /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:135 - cannot load such file -- abrt
Jun 07 15:59:14 srv-sub-dash ruby[15566]: Exception `Gem::MissingSpecError' at /usr/local/share/ruby/site_ruby/rubygems/dependency.rb:308 - Gem::MissingSpecError
Jun 07 15:59:14 srv-sub-dash ruby[15566]: /usr/local/share/ruby/site_ruby/rubygems/dependency.rb:308:in `to_specs': Could not find 'smashing' (>= 0) among 50 total gem(s) (Gem::MissingSpecError)
Jun 07 15:59:14 srv-sub-dash ruby[15566]: Checked in 'GEM_PATH=/root/.gem/ruby:/usr/share/gems:/usr/local/share/gems', execute `gem env` for more information
Jun 07 15:59:14 srv-sub-dash ruby[15566]: from /usr/local/share/ruby/site_ruby/rubygems/dependency.rb:320:in `to_spec'
Jun 07 15:59:14 srv-sub-dash ruby[15566]: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_gem.rb:65:in `gem'
Jun 07 15:59:14 srv-sub-dash ruby[15566]: from /home/dashing/.rbenv/versions/2.2.7/bin/smashing:22:in `<main>'
Jun 07 15:59:14 srv-sub-dash systemd[1]: dashing.service: main process exited, code=exited, status=1/FAILURE
Jun 07 15:59:14 srv-sub-dash systemd[1]: Unit dashing.service entered failed state.
Jun 07 15:59:14 srv-sub-dash systemd[1]: dashing.service failed.
```

**Comment by dfbm** [comment]
Well, from the output it seems that the environment is different. Login as the dashboard user, enter "export" (if using bash) and check which variables may be missing.
