### ISSUE TITLE
Loading a widget with an empty name throws an exception.

### ISSUE THREAD

**Issue by YtvwlD** [Smashing/smashing#97]
Requesting `/widgets/.html` throws a TypeError. This doesn't seem like a serious bug, but it may be a bit interesting.

The problem seems to lie [here](https://github.com/Smashing/smashing/blob/fa7cf47e28a4ac1636e947c269ed83abe49a1491/lib/dashing/app.rb#L123):
```ruby
get '/views/:widget?.html' do
  protected!
  tilt_html_engines.each do |suffix, engines|
    file = File.join(settings.root, "widgets", params[:widget], "#{params[:widget]}.#{suffix}")
    return engines.first.new(file).render if File.exist? file
  end
  "Drats! Unable to find a widget file named: #{params[:widget]} to render."
end
```

This is the full stacktrace:
```
TypeError: no implicit conversion of nil into String
  from dashing/app.rb:124:in `join'
  from dashing/app.rb:124:in `block (2 levels) in <top (required)>'
  from dashing/app.rb:123:in `each'
  from dashing/app.rb:123:in `block in <top (required)>'
  from sinatra/base.rb:1632:in `call'
  from sinatra/base.rb:1632:in `block in compile!'
  from sinatra/base.rb:991:in `block (3 levels) in route!'
  from sinatra/base.rb:1010:in `route_eval'
  from sinatra/base.rb:991:in `block (2 levels) in route!'
  from sinatra/base.rb:1037:in `block in process_route'
  from sinatra/base.rb:1035:in `catch'
  from sinatra/base.rb:1035:in `process_route'
  from sinatra/base.rb:989:in `block in route!'
  from sinatra/base.rb:988:in `each'
  from sinatra/base.rb:988:in `route!'
  from sinatra/base.rb:1094:in `block in dispatch!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:1091:in `dispatch!'
  from sinatra/base.rb:923:in `block in call!'
  from sinatra/base.rb:1073:in `block in invoke'
  from sinatra/base.rb:1073:in `catch'
  from sinatra/base.rb:1073:in `invoke'
  from sinatra/base.rb:923:in `call!'
  from sinatra/base.rb:913:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/base.rb:50:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from rack/logger.rb:15:in `call'
  from rack/common_logger.rb:33:in `call'
  from sinatra/base.rb:231:in `call'
  from sinatra/base.rb:224:in `call'
  from rack/head.rb:12:in `call'
  from rack/method_override.rb:22:in `call'
  from sinatra/show_exceptions.rb:22:in `call'
  from sinatra/base.rb:194:in `call'
  from sinatra/base.rb:1955:in `call'
  from sinatra/base.rb:1499:in `block in call'
  from sinatra/base.rb:1726:in `synchronize'
  from sinatra/base.rb:1499:in `call'
  from rack/urlmap.rb:68:in `block in call'
  from rack/urlmap.rb:53:in `each'
  from rack/urlmap.rb:53:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from thin/connection.rb:86:in `block in pre_process'
  from thin/connection.rb:84:in `catch'
  from thin/connection.rb:84:in `pre_process'
  from thin/connection.rb:53:in `process'
  from thin/connection.rb:39:in `receive_data'
  from eventmachine.rb:194:in `run_machine'
  from eventmachine.rb:194:in `run'
  from thin/backends/base.rb:73:in `start'
  from thin/server.rb:162:in `start'
  from thin/controllers/controller.rb:87:in `start'
  from thin/runner.rb:203:in `run_command'
  from thin/runner.rb:159:in `run!'
  from vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
  from vendor/bundle/ruby/2.4.0/bin/thin:23:in `load'
  from vendor/bundle/ruby/2.4.0/bin/thin:23:in `<top (required)>'
  from bundler/cli/exec.rb:75:in `load'
  from bundler/cli/exec.rb:75:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:424:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:122:in `with_friendly_errors'
  from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
  from /usr/bin/bundle:23:in `load'
  from /usr/bin/bundle:23:in `<main>'
```

**Comment by kinow** [comment]
Hi @YtvwlD 

Isn't that the same exception you would get when requesting a non existing widget? If so, I think throwing the exception is fine. Trying to handle corner cases would add code that could cause other issues, besides having to be tested/updated/etc.

What do you think?

**Comment by tylermauthe** [comment]
Hello! Thanks for your interest in using Smashing. Unfortunately, the bandwidth available to support issues is greatly exceeded by the number of issues reported.

Due to this limitation, the maintainers of Smashing do not answer support requests submitted as GitHub issues. This is stated in the [CONTRIBUTING.d](https://github.com/Smashing/smashing/blob/master/CONTRIBUTING.md#have-an-issue), please read that for more details.

Thanks!

**Comment by YtvwlD** [comment]
Hi @kinow

This is a different exception.

Loading a non-existing widget (eg. `/views/foo.html`) results in a page which contains the message following message:

> Drats! Unable to find a widget file named: foo to render.

Loading `/views/.html` throws the following exception:

> TypeError - no implicit conversion of nil into String

(also, this displays a debug page which I should probably have disabled)
